# Site settings
url: https://thebytesized.com
baseurl: /
title: The Byte-sized
logo: /img/logos/logo-the-byte-sized-green.png
tagline: Tailored, efficient, and scalable digital solutions
description: "The Byte Sized is a tech company specializing in app development, web development, backend solutions, and IT consulting. We deliver tailored, efficient, and scalable digital solutions, helping businesses transform their ideas into cutting-edge technology."
email: claudio.cortese@thebytesized.com


# Team names, titles and social links
people:
- name: Ciro Carandente
  pic: ciro_carandente
  color: 9ee52d
  position: Founder & CEO
  description: With extensive experience in software development, gained in prestigious environments such as Luxottica and the Italian Red Cross, he demonstrates remarkable ability in leading teams toward important goals, utilizing a wide range of technologies. He is capable of independently managing his workload, ensuring the respect of deadlines and objectives, and communicates effectively with clients and users. His teamwork skills, developed both in academic and professional settings, make him a reliable and highly competent professional.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ciro-carandente/
    - title: github
      url: https://github.com/codakkk

- name: Claudio Cortese
  pic: claudio_cortese
  color: 0170c5
  position: Founder & CTO
  description: Extensive experience in software development at prestigious companies such as Luxottica, Namirial, and the Italian Red Cross, he excels in leading teams to success while working with diverse technology stacks. He demonstrates autonomy in work organization, meeting deadlines and objectives, and communicates clearly with clients and users. His experience in teamwork, both academic and professional, distinguishes him as a reliable and competent professional.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/claudio-cortese/
    - title: github
      url: https://github.com/CloudPower97
    - title: stack-overflow
      url: https://stackoverflow.com/users/5767099/claudio-cortese

# - name: Francesco Orlando
#   pic: francesco_orlando
#   color: E95420
#   position: AI Engineer & Software Developer
#   description: Francesco's passion for technology began in high school, where he experimented with computer science and robotics, competing in national tournaments. He graduated in Computer Science and is now pursuing a master's degree in Artificial Intelligence and Data Science 🎓. At ByteSized, he is an artificial intelligence developer 💻, specializing in computer vision and natural language processing for digital identity verification. Francesco has managed to perfectly combine hobby and work; technology and innovation drive him to overcome boundaries and leave his mark in the world of technology! 🤖✨ 
#   social:
#     - title: github
#       url: https://github.com/Effeo
#     - title: linkedin
#       url: https://www.linkedin.com/in/francesco-orlando-8b8851232

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: Via Ponti Rossi 259
  - line: Napoli, NA 80141

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap