# Site settings
url: https://thebytesized.com
baseurl: /
title: The Byte-sized
logo: /img/logos/logo-the-byte-sized-green.png
tagline: Tailored, efficient, and scalable digital solutions
description: "The Byte Sized is a tech company specializing in app development, web development, backend solutions, and IT consulting. We deliver tailored, efficient, and scalable digital solutions, helping businesses transform their ideas into cutting-edge technology."
email: claudio.cortese@thebytesized.com


# Team names, titles and social links
people:
- name: Claudio Cortese
  pic: claudio_cortese
  color: 0170c5
  position: Founder & Lead Developer
  description: Extensive experience in software development at prestigious companies such as Luxottica, Namirial, and the Italian Red Cross, he excels in leading teams to success while working with diverse technology stacks. He demonstrates autonomy in work organization, meeting deadlines and objectives, and communicates clearly with clients and users. His experience in teamwork, both academic and professional, distinguishes him as a reliable and competent professional.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/claudio-cortese/
    - title: github
      url: https://github.com/CloudPower97
    - title: stack-overflow
      url: https://stackoverflow.com/users/5767099/claudio-cortese

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/the-byte-sized/

# Postal address (add as many lines as necessary)
address:
  - line: Via Ponti Rossi 259
  - line: Napoli, NA 80141

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap